apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: ray-head-monitor
  namespace: kube-prometheus-stack
  labels:
    release: kube-prometheus-stack
spec:
  jobLabel: ray-head
  namespaceSelector:
    matchNames:
      - ray-system
  selector:
    matchLabels:
      ray.io/node-type: head
  endpoints:
    - port: metrics
      interval: 5s
  targetLabels:
    - ray.io/cluster
