# KubeCost WebUI -> kubectl port-forward --namespace kubecost deployment/kubecost-cost-analyzer 9090

global:
  prometheus:
    enabled: true
    fqdn: http://cost-analyzer-prometheus-server.default.svc

  grafana:
    enabled: true
    domainName: cost-analyzer-grafana.default.svc
    scheme: "http"
    proxy: true

kubecostFrontend:
  image: public.ecr.aws/kubecost/frontend
  resources:
    requests:
      cpu: "200m"
      memory: "512Mi"

kubecostMetrics:
  emitPodAnnotations: true
  emitNamespaceAnnotations: true

kubecostModel:
  image: public.ecr.aws/kubecost/cost-model
  resources:
    requests:
      cpu: "500m"
      memory: "512Mi"

forecasting:
  fullImageName: public.ecr.aws/kubecost/kubecost-modeling:v0.1.6

networkCosts:
  image:
    repository: public.ecr.aws/kubecost/kubecost-network-costs

clusterController:
  image:
    repository: public.ecr.aws/kubecost/cluster-controller

prometheus:
  server:
    image:
      repository: public.ecr.aws/kubecost/prometheus

  configmapReload:
    prometheus:
      image:
        repository: public.ecr.aws/kubecost/prometheus-config-reloader

reporting:
  productAnalytics: false

# Define persistence volume for cost-analyzer
persistentVolume:
  size: 32Gi
  dbSize: 32.0Gi
  enabled: true

ingress:
  className: nginx
  enabled: true
  hosts:
  - kubecost.domainsandbox.net
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/proxy-body-size: "512m"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
    nginx.ingress.kubernetes.io/rewrite-target: "/"
